In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [13]:
df = pd.read_csv("netflix1.csv")
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020.0,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021.0,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021.0,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021.0,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993.0,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [14]:
df.isna().sum()
df.info()
df.count()
df['date_added'].iloc[12]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8789 non-null   object
 6   release_year  8789 non-null   float64
 7   rating        8790 non-null   object
 8   duration      8788 non-null   object
 9   listed_in     8790 non-null   object
dtypes: float64(1), object(9)
memory usage: 686.8+ KB

'5/21/2021'

In [15]:
df[df['director']=='Not Given']  = 'Unknown'
df[df['country']=='Not Given']  = 'Unknown'

/tmp/ipykernel_9065/4062078266.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df[df['director']=='Not Given']  = 'Unknown'

In [16]:
df['date_added'] = df['date_added'].str.strip()
df['date_added']  = df['date_added'].str.replace('/','-',regex=False)
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df = df.dropna(subset=['date_added'])

df['date_added'][df['date_added'].isna()]
df['date_added'].iloc[12]

Timestamp('2021-07-13 00:00:00')

In [17]:
# This shows you the original data for the rows that failed to convert
print(df[df['date_added'].isna()])

Empty DataFrame
Columns: [show_id, type, title, director, country, date_added, release_year, rating, duration, listed_in]
Index: []

In [18]:
df['release_year'] = df['release_year'].astype(int)

In [19]:
df['listed_in'] = df['listed_in'].str.split(',')
df

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,[Documentaries]
1,s3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"[Crime TV Shows, International TV Shows, TV ..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"[TV Dramas, TV Horror, TV Mysteries]"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"[Children & Family Movies, Comedies]"
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"[Dramas, Independent Movies, International M..."
...,...,...,...,...,...,...,...,...,...,...
6565,s3351,Movie,True: Grabbleapple Harvest,"Mark Thornton, Todd Kauffman",Canada,2019-11-01,2019,TV-Y,24 min,[Children & Family Movies]
6566,s3509,Movie,True: Tricky Treat Day,"Mark Thornton, Todd Kauffman",Canada,2019-09-20,2019,TV-Y,24 min,[Children & Family Movies]
6567,s3554,TV Show,True and the Rainbow Kingdom,"Mark Thornton, Todd Kauffman",United States,2019-08-30,2019,TV-Y,3 Seasons,[Kids' TV]
6568,s4241,Movie,Sam Kinison: The Scream Continues,Walter C. Miller,United States,2018-12-31,2016,TV-MA,29 min,[Documentaries]
6569,s1315,TV Show,Chappelle's Show,Stan Lathan,United States,2021-02-12,2005,TV-MA,2 Seasons,[TV Comedies]

In [20]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,[Documentaries]
1,s3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"[Crime TV Shows, International TV Shows, TV ..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"[TV Dramas, TV Horror, TV Mysteries]"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"[Children & Family Movies, Comedies]"
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"[Dramas, Independent Movies, International M..."

In [21]:
# # 1. Split by comma
# # 2. Explode into individual rows
# # 3. Strip leading/trailing spaces (CRITICAL STEP)
# # 4. Count unique values
# clean_counts = df['listed_in'].str.split(',').explode().str.strip().value_counts()

# print(clean_counts)
# # join then split with strip or use get_dummies on the clean series
# genre_dummies = df['listed_in'].str.get_dummies(sep=', ')
# df = pd.concat([df, genre_dummies], axis=1)


# # # Flatten the list so each genre has its own row
# # exploded_df = df.explode('listed_in')

# # # See the unique genres and how many times they appear
# # print(exploded_df['listed_in'].value_counts())


# # # Join the list back with a separator then use get_dummies
# # genre_columns = df['listed_in'].str.join('|').str.get_dummies()

# # # Add these new columns back to your original dataframe
# # df = pd.concat([df, genre_columns], axis=1)
# # df

In [22]:
# df['Comedies'] = df['listed_in'].apply(lambda x: True if 'Comedies' in x else False)
# df['International Movies'] = df['listed_in'].apply(lambda x: True if 'International Movies' in x else False)
# df['Dramas'] = df['listed_in'].apply(lambda x: True if 'Dramas' in x else False)

In [27]:
comedy = df[df['listed_in'].apply(lambda x: 'Comedies' in x)]
comedy.head()
print(df['rating'].unique())



df.head()

['PG-13' 'TV-MA' 'TV-PG' 'TV-14' 'TV-Y7' 'TV-Y' 'TV-G' 'PG' 'R' 'G'
 'NC-17' 'NR' 'TV-Y7-FV' 'UR']

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,[Documentaries]
1,s3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"[Crime TV Shows, International TV Shows, TV ..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"[TV Dramas, TV Horror, TV Mysteries]"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"[Children & Family Movies, Comedies]"
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"[Dramas, Independent Movies, International M..."
...,...,...,...,...,...,...,...,...,...,...
6565,s3351,Movie,True: Grabbleapple Harvest,"Mark Thornton, Todd Kauffman",Canada,2019-11-01,2019,TV-Y,24 min,[Children & Family Movies]
6566,s3509,Movie,True: Tricky Treat Day,"Mark Thornton, Todd Kauffman",Canada,2019-09-20,2019,TV-Y,24 min,[Children & Family Movies]
6567,s3554,TV Show,True and the Rainbow Kingdom,"Mark Thornton, Todd Kauffman",United States,2019-08-30,2019,TV-Y,3 Seasons,[Kids' TV]
6568,s4241,Movie,Sam Kinison: The Scream Continues,Walter C. Miller,United States,2018-12-31,2016,TV-MA,29 min,[Documentaries]
6569,s1315,TV Show,Chappelle's Show,Stan Lathan,United States,2021-02-12,2005,TV-MA,2 Seasons,[TV Comedies]

In [55]:
# df['Total_seasons'] = df['duration'].str.extract('(\d+) Season[s]?').astype(float)
# df['Total_minutes'] = df['duration'].str.extract('(\d+) min').astype(float)
# df['Total_seasons'] = df['Total_seasons'].fillna(0).astype(int)
# df['Total_minutes'] = df['Total_minutes'].fillna(0).astype(int)
# df.drop(columns=['duration'], inplace=True)
# df

In [58]:
df.isna().sum()
df.to_csv("netflix_cleaned.csv", index=False)